name: Bomber SBOM Vulnerability Scan

on:
  push:
    paths:
      - '**/*.json'  # Trigger on SBOM JSON files
      - '**/*-sbom.xml'   # Also trigger on XML format SBOMs
  workflow_dispatch:  # Allow manual triggering

env:
  BOMBER_PROVIDER_USERNAME: ${{ secrets.BOMBER_PROVIDER_USERNAME }}
  BOMBER_PROVIDER_TOKEN: ${{ secrets.BOMBER_PROVIDER_TOKEN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bomber
        run: |
          wget https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_linux_amd64.tar.gz
          tar xzf bomber_0.5.1_linux_amd64.tar.gz bomber
          chmod +x bomber
          sudo mv bomber /usr/local/bin/
          mkdir -p scan-results

      - name: Run Bomber scan
        run: |
          # Create scan results directory
          mkdir -p scan-results
          
          # Find and scan all SBOM files
          for file in $(find . -maxdepth 1 -type f \( -name "*.json" -o -name "*-sbom.xml" \)); do
            echo "Scanning SBOM: $file"
            echo "Current directory: $(pwd)"
            echo "Contents before scan:"
            ls -la
            
            # Run scans with explicit output paths
            bomber scan "$file" --output html --provider ossindex
            bomber scan "$file" --output json --provider ossindex
            bomber scan "$file" --output md --provider ossindex
            
            echo "Contents after scan:"
            ls -la
            
            # Move any generated files to scan-results directory
            mv -v *bomber-results.* scan-results/ 2>/dev/null || echo "No results to move for $file"
          done
          
          echo "Final contents of scan-results directory:"
          ls -la scan-results/

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: bomber-scan-results
          path: scan-results/*bomber-results.*
          retention-days: 90
          if-no-files-found: warn

      - name: Generate summary
        run: |
          mkdir -p scan-results
          {
            echo "### Bomber SBOM Scan Summary"
            echo ""
            echo "#### Environment Information"
            echo '```'
            bomber scan --help | head -n 1
            echo '```'
            
            echo -e "\n#### Input Files"
            echo '```'
            find . -maxdepth 1 -type f \( -name "*.json" -o -name "*-sbom.xml" \)
            echo '```'
            
            echo -e "\n#### Generated Reports"
            echo '```'
            ls -la scan-results/
            echo '```'
            
            if [ -f "scan-results/"*"-bomber-results.md" ]; then
              echo -e "\n#### Scan Results"
              cat scan-results/*-bomber-results.md
            fi
          } > scan-results/summary.md

          echo "Summary contents:"
          cat scan-results/summary.md
