name: SBOM Bomber Scan

on:
  push:
    paths:
      - '**/*.json'  # Trigger on SBOM JSON files
      - '**/*.xml'   # Also trigger on XML format SBOMs
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bomber
        run: |
          # Download latest bomber release
          curl -s https://api.github.com/repos/devops-kung-fu/bomber/releases/latest | \
          grep "browser_download_url.*linux_amd64.tar.gz" | \
          cut -d : -f 2,3 | \
          tr -d \" | \
          wget -qi -
          
          # Extract and install bomber
          tar xzf bomber_*_linux_amd64.tar.gz bomber
          chmod +x bomber
          sudo mv bomber /usr/local/bin/
          
          # Verify installation
          bomber version

      - name: Create results directory
        run: mkdir -p scan-results

      - name: Scan SBOMs
        run: |
          # Find all SBOM files and scan them
          for sbom in $(find . -type f \( -name "*.json" -o -name "*.xml" \)); do
            echo "==== Starting scan for: $sbom ===="
            
            # Generate output filename
            output_base="scan-results/$(basename $sbom)"
            
            # Run bomber scan with multiple output formats
            bomber scan "$sbom" \
              --output html,json,md \
              --severity low \
              || echo "Warning: Scan completed with findings"
            
            # Move generated files to our results directory
            mv *-bomber-results.* scan-results/ 2>/dev/null || true
            
            echo "==== Completed scan for: $sbom ===="
          done

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bomber-scan-results
          path: scan-results/
          retention-days: 90
          if-no-files-found: warn

      - name: Generate summary
        if: always()
        run: |
          echo "### Bomber SBOM Scan Summary" > scan-results/summary.md
          echo "" >> scan-results/summary.md
          
          echo "#### Environment Information" >> scan-results/summary.md
          echo '```' >> scan-results/summary.md
          bomber version >> scan-results/summary.md
          echo '```' >> scan-results/summary.md
          
          echo "\n#### Found SBOM Files" >> scan-results/summary.md
          echo '```' >> scan-results/summary.md
          find . -type f \( -name "*.json" -o -name "*.xml" \) -ls >> scan-results/summary.md
          echo '```' >> scan-results/summary.md
          
          echo "\n#### Scan Results" >> scan-results/summary.md
          for file in scan-results/*-bomber-results.md; do
            if [ -f "$file" ]; then
              echo "\n#### Results from $(basename $file)" >> scan-results/summary.md
              cat "$file" >> scan-results/summary.md
              echo "" >> scan-results/summary.md
            fi
          done
          
          cat scan-results/summary.md
