name: SBOM Bomber Scan

on:
  push:
    paths:
      - '**/*.json'            # Any JSON files
      - '**/*-sbom.xml'        # Any SBOM XML files
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bomber
        run: |
          wget https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_linux_amd64.tar.gz
          tar xzf bomber_0.5.1_linux_amd64.tar.gz bomber
          chmod +x bomber
          sudo mv bomber /usr/local/bin/
          bomber version

      - name: List SBOM files
        run: |
          echo "Current directory: $(pwd)"
          echo "Found files to scan:"
          find . -type f \( -name "*.json" -o -name "*-sbom.xml" \)

      - name: Create results directory
        run: |
          mkdir -p scan-results
          echo "Created scan-results directory: $(ls -la scan-results)"

      - name: Scan SBOMs
        run: |
          # Find and scan all JSON and SBOM files
          find . -type f \( -name "*.json" -o -name "*-sbom.xml" \) -print0 | while IFS= read -r -d '' file; do
            echo "Starting scan of: $file"
            bomber scan "$file" --output html || true
            bomber scan "$file" --output json || true
            bomber scan "$file" --output md || true
          done
          
          # Move all generated results to scan-results directory
          mv *bomber-results.* scan-results/ || echo "No results to move"
          
          # List generated files
          echo "Generated files in scan-results:"
          ls -la scan-results/

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bomber-scan-results
          path: |
            scan-results/*bomber-results.*
          retention-days: 90
          if-no-files-found: warn

      - name: Generate summary
        if: always()
        run: |
          {
            echo "### Bomber SBOM Scan Summary"
            echo ""
            echo "#### Environment Information"
            echo '```'
            bomber version
            echo '```'
            
            echo -e "\n#### Input Files"
            echo '```'
            find . -maxdepth 1 -type f \( -name "*.json" -o -name "*-sbom.xml" \)
            echo '```'
            
            echo -e "\n#### Generated Reports"
            echo '```'
            ls -la scan-results/
            echo '```'
            
            if [ -f "scan-results/"*"-bomber-results.md" ]; then
              echo -e "\n#### Scan Results"
              cat scan-results/*-bomber-results.md
            fi
          } > scan-results/summary.md
          
          echo "Summary contents:"
          cat scan-results/summary.md
