name: SBOM Vulnerability Scan

on:
  push:
    paths:
      - '**/*.json'  # Trigger on SBOM JSON files
      - '**/*.xml'   # Also trigger on XML format SBOMs
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype version

      - name: Create results directory
        run: mkdir -p scan-results

      - name: Scan SBOMs
        run: |
          # Find all SBOM files and scan them
          find . -type f \( -name "*.json" -o -name "*.xml" \) -exec sh -c '
            echo "Scanning SBOM: {}"
            mkdir -p scan-results
            grype sbom:{} --output table > "scan-results/$(basename {}).scan-results.txt" || echo "Warning: Scan failed for {}"
          ' \;
        continue-on-error: true

      - name: Upload scan results
        if: always()  # Upload results even if scanning fails
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-scan-results
          path: scan-results/
          retention-days: 90
          if-no-files-found: warn

      - name: Check for high severity vulnerabilities
        run: |
          if [ -d scan-results ] && [ "$(ls -A scan-results)" ]; then
            if grep -i "High\|Critical" ./scan-results/*.scan-results.txt; then
              echo "⚠️ High or Critical severity vulnerabilities found!"
              exit 1
            else
              echo "✅ No high severity vulnerabilities found"
            fi
          else
            echo "⚠️ No scan results found to analyze"
            exit 1
          fi
